// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk5yhlANhWSCLpWPqnSwv8J9NSJg4YVYc',
    appId: '1:629537487890:web:9d3844d31e1749f677eccb',
    messagingSenderId: '629537487890',
    projectId: 'ecommerceapp-582a0',
    authDomain: 'ecommerceapp-582a0.firebaseapp.com',
    storageBucket: 'ecommerceapp-582a0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdT8B2Y2TlPYu4YrZGhFa-T81B-fDOgS4',
    appId: '1:629537487890:android:227367afa18913c477eccb',
    messagingSenderId: '629537487890',
    projectId: 'ecommerceapp-582a0',
    storageBucket: 'ecommerceapp-582a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0rUMwmVssOZMzgPsoYCFCB_J3GDnB3Gc',
    appId: '1:629537487890:ios:3e574056eec8db0f77eccb',
    messagingSenderId: '629537487890',
    projectId: 'ecommerceapp-582a0',
    storageBucket: 'ecommerceapp-582a0.firebasestorage.app',
    androidClientId: '629537487890-hek18huld9dlr5eh0r53u7bvr8kummpm.apps.googleusercontent.com',
    iosClientId: '629537487890-38p4o3u83ak62sbt986pdq2kescle2j1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

}